### ISSUE TITLE
pip3 install failed with error code 1

### ISSUE THREAD

**Issue by wjsbgsnwss** [cclauss/Python2-and-Python3-in-Docker#2]
Seems like the python3 'print' syntax was not followed properly, but not sure why.

/ # pip3 --no-cache-dir -v install BeautifulSoup
Collecting BeautifulSoup
  1 location(s) to search for versions of BeautifulSoup:
  * https://pypi.python.org/simple/beautifulsoup/
  Getting page https://pypi.python.org/simple/beautifulsoup/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/beautifulsoup/ HTTP/1.1" 200 316
  Analyzing links from page https://pypi.python.org/simple/beautifulsoup/
    Found link https://pypi.python.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz#md5=44656527ef3ac9874ac4d1c9f35f70ee (from https://pypi.python.org/simple/beautifulsoup/), version: 3.2.1
    Found link https://pypi.python.org/packages/33/fe/15326560884f20d792d3ffc7fe8f639aab88647c9d46509a240d9bfbb6b1/BeautifulSoup-3.2.0.tar.gz#md5=9c0f5d246ecfcf5f0905a47b1466e140 (from https://pypi.python.org/simple/beautifulsoup/), version: 3.2.0
  Using version 3.2.1 (newest of versions: 3.2.0, 3.2.1)
  "GET /packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz HTTP/1.1" 200 31220
  Downloading BeautifulSoup-3.2.1.tar.gz
  Downloading from URL https://pypi.python.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz#md5=44656527ef3ac9874ac4d1c9f35f70ee (from https://pypi.python.org/simple/beautifulsoup/)
  Running setup.py (path:/tmp/pip-build-l5yv0wg8/BeautifulSoup/setup.py) egg_info for package BeautifulSoup
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l5yv0wg8/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-l5yv0wg8/BeautifulSoup/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-l5yv0wg8/BeautifulSoup/

**Comment by cclauss** [comment]
`pip3 install beautifulsoup4`   # all lowercase with the 4 on the end.
