### ISSUE TITLE
Support for Python 3.7

### ISSUE THREAD

**Issue by ghost** [cclauss/Python2-and-Python3-in-Docker#3]
If possible can you please add the support for Python 3.7 in this Docker image so that we can have Python 2.7. Python 3.6 and Python 3.7 in one image or please let me know how can we add this support for Python 3.7 in this image.

**Comment by cclauss** [comment]
https://github.com/cclauss/Python2-and-Python3-in-Docker/commit/dfa38d773a2e3e0cce2d975e3a8b26e365c33722 adds support for Python 3.7.1 but removes support for Python 3.6.  Does that satisfy your needs or do you really need two different versions of Python 3 in the same image?

**Comment by ghost** [comment]
Thanks a lot for your quick and prompt response. 

Actually in my use case I need the support for Py 2.7, Py 3.6 and Py 3.7 in the same docker image file.

Also I have a basic question, instead of doing this lengthy thing, I was wondering why we can not do following 
FROM python:3.7.0-alpine
FROM python:3.6.0-alpine
FROM python:2.7.0-alpine

I tried doing this but the next one overrides the previous one so in the end only python 2.7 is available. I am new to Dockers so asking this basic question.

**Comment by ghost** [comment]
Also I tried this new image for 3.7 but it is not working, getting following error :-

![image](https://user-images.githubusercontent.com/11605748/49064677-84e6a600-f1d0-11e8-84f6-d7bfede34d49.png)

**Comment by cclauss** [comment]
The Docker docs are quite clear that only one __FROM__ statement is allowed in a Dockerfile.

Please try again with the changes just made.

**Comment by ghost** [comment]
Tried again and getting the same error......infact I tried this yesterday by changing pip3.6 to pip3.7 but it did not worked......

![image](https://user-images.githubusercontent.com/11605748/49099258-da996d80-f225-11e8-9a9d-bf7f408f94cd.png)

**Comment by mmacvicar-splunk** [comment]
I'm seeing the same 
`+ cp /usr/local/bin/pip3.7 /usr/local/bin/pip3
cp: can't stat '/usr/local/bin/pip3.7': No such file or directory
`

I have a PR that fixes the issue here https://github.com/cclauss/Python2-and-Python3-in-Docker/pull/4

`pip install --force-reinstall` was deleting pip3 and pip3.7 binaries.

**Comment by mmacvicar-splunk** [comment]
pip3 issue fixed with merge https://github.com/cclauss/Python2-and-Python3-in-Docker/commit/dc2a354bc74c89913c52456c75906a14e4f7cfee
